[project]
name = "sonolus_fastapi"
version = "0.1.0"
description = "FastAPI wrapper for Sonolus server creation and management"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.4",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
